# Generated by Django 5.0 on 2024-02-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_converted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted',
        ),
    ]
